FROM python:3.11-slim

WORKDIR /app
COPY src/requirements.txt .

RUN apt-get update && apt-get install -y ffmpeg libgl1 && \
    pip install --no-cache-dir -r requirements.txt

# copy code (for prod) – dev uses bind-mount
COPY src ./src

ENV PYTHONUNBUFFERED=1
CMD ["python", "-u", "src/inference.py"]